#!/bin/sh
#
# @name Inverted Coaxial Servo Drone
#
# @type Coaxial
#
# @class Copter
#
# @maintainer Your Name <your.email@example.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults
param set-default MAV_TYPE 9 # Rocket

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=tvc}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1


# Configure as bicopter with servo tilt
param set-default CA_AIRFRAME 13 # Specify custom airframe

# Set motor count (2 motors, 2 servos)
param set-default CA_ROTOR_COUNT 2
param set-default CA_SV_TL_COUNT 2

# First motor (top coaxial)
param set-default CA_TVC_M0_CT 0.0000048449
param set-default CA_TVC_M0_KMR 0.001 # Temporary positive value for testing

# Second motor (bottom coaxial)
param set-default CA_TVC_M1_CT 0.0000048449
param set-default CA_TVC_M1_KMR -0.001	# Temporary negative value for testing

# Servo 0 (Roll control)
param set-default CA_TVC_S0_GAIN 1
param set-default CA_TVC_S0_MAX 1	# 30 degrees in radians
param set-default CA_TVC_S0_MIN -1
param set-default CA_TVC_S0_GEO_A 0.05
param set-default CA_TVC_S0_GEO_B 0.01
param set-default CA_TVC_S0_GEO_C 0.06
param set-default CA_TVC_S0_GEO_D 0.02
param set-default CA_TVC_S0_GEO_E 0.06

# Servo 1 (Pitch control)
param set-default CA_TVC_S1_GAIN 1
param set-default CA_TVC_S1_MAX 1
param set-default CA_TVC_S1_MIN -1
param set-default CA_TVC_S1_GEO_A 0.05
param set-default CA_TVC_S1_GEO_B 0.01
param set-default CA_TVC_S1_GEO_C 0.06
param set-default CA_TVC_S1_GEO_D 0.02
param set-default CA_TVC_S1_GEO_E 0.06

param set-default CA_TVC_COM_DIS 0.275170

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102

param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000

param set-default SIM_GZ_SV_FUNC1 201	# roll control servo
param set-default SIM_GZ_SV_FUNC2 202	# pitch control servo

# To avoid failsafe errors during simulation
param set FD_FAIL_R 180

